# Generated by Django 4.2.28 on 2026-02-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='Chat Id')),
                ('user1', models.IntegerField(verbose_name='Пользователь чата 1')),
                ('user2', models.IntegerField(verbose_name='Пользователь чата 2')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(verbose_name='Message Id')),
                ('from_user_id', models.IntegerField(verbose_name='From User Id')),
                ('to_user_id', models.IntegerField(verbose_name='From User Id')),
            ],
        ),
        migrations.CreateModel(
            name='UserTg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User Id пользователя')),
                ('chat_id', models.IntegerField(verbose_name='Chat Id пользователя с ботом')),
            ],
        ),
    ]
