# Generated by Django 4.2.28 on 2026-02-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0002_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_user_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_user_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(unique=True, verbose_name='Message Id'),
        ),
    ]
