# Generated by Django 4.2.28 on 2026-02-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0003_remove_message_from_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.AddField(
            model_name='message',
            name='username_from',
            field=models.TextField(default='', verbose_name='Username sender'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default='Не текстовое сообщение', verbose_name='Text'),
        ),
    ]
