# Generated by Django 4.2.28 on 2026-02-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0004_delete_chat_message_username_from_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertg',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='Username'),
        ),
    ]
