# Generated by Django 4.2.28 on 2026-02-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0005_usertg_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='usertg',
            options={'verbose_name': 'Пользователь бота', 'verbose_name_plural': 'Пользователи бота'},
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default='Не текстовое сообщение', null=True, verbose_name='Text'),
        ),
    ]
