# Generated by Django 4.2.28 on 2026-02-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0006_alter_message_options_alter_usertg_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='message',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='First name sender'),
        ),
        migrations.AlterField(
            model_name='message',
            name='username_from',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Username sender'),
        ),
    ]
