# Generated by Django 4.2.28 on 2026-02-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0007_message_created_at_message_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chat id'),
        ),
    ]
