# Generated by Django 4.2.28 on 2026-02-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0008_message_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertg',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='First name sender'),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Username'),
        ),
    ]
