# Generated by Django 4.2.28 on 2026-02-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0009_usertg_first_name_alter_usertg_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='business_connection_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Business connection id'),
        ),
    ]
