# Generated by Django 4.2.28 on 2026-03-03 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webhook_tg', '0010_message_business_connection_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChatFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Пользователь видит только сообщения с этим chat_id', verbose_name='Chat id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_chat_filter', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к чату (админка)',
                'verbose_name_plural': 'Доступ к чатам (админка)',
            },
        ),
    ]
