# Generated by Django 4.2.28 on 2026-03-06 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webhook_tg', '0012_alter_adminchatfilter_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminchatfilter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='adminchatfilter',
            name='business_connection_id',
            field=models.CharField(blank=True, help_text='Если указан — доступ только к сообщениям с этим business_connection_id и chat_id. Пусто — все сообщения этого chat_id.', max_length=255, null=True, verbose_name='Business connection id'),
        ),
        migrations.AddField(
            model_name='message',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='Текст к файлу'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File id'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'Неизвестно'), ('PHOTO', 'Фото'), ('AUDIO', 'Аудио'), ('VIDEO', 'Видео'), ('DOCUMENT', 'Документ')], default='UNKNOWN', max_length=20, null=True, verbose_name='Тип файла'),
        ),
        migrations.AddField(
            model_name='message',
            name='payload',
            field=models.TextField(blank=True, default='', null=True, verbose_name='payload'),
        ),
        migrations.AlterField(
            model_name='adminchatfilter',
            name='chat_id',
            field=models.BigIntegerField(help_text='Chat id из Telegram', verbose_name='Chat id'),
        ),
        migrations.AlterUniqueTogether(
            name='adminchatfilter',
            unique_together={('user', 'chat_id', 'business_connection_id')},
        ),
    ]
