# Generated by Django 4.2.28 on 2026-03-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0013_alter_adminchatfilter_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Text'),
        ),
    ]
